[project]
name = "myutilspkg"
version = "0.1.0"
description = "my utilities package"
requires-python = ">=3.13"

[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"